Add official Dockerfile
ACINQ/phoenixd pull request #17
Opened 2024-03-26 20:25 UTC by pm47

Follow-up to #1.

I think building native binaries on docker is not the right approach. It's better to run on the jvm: easier build, faster runtime and compatible with linux arm64, which we don't support otherwise.

TODO:
- remove `lightning-kmp` build once https://github.com/ACINQ/lightning-kmp/pull/622 is merged
- remove `RUN mkdir .phoenix` once #15 is merged

cc @sethforprivacy

2024-03-26 21:00 UTC, sethforprivacy commented
Will take a deeper look asap, but at first glance I love this approach!

2024-03-26 22:01 UTC, tsmith123 commented
I'm getting "ERROR: failed to solve: eclipse-temurin:17-jre-alpine: no match for platform in manifest: not found" running on an M2 Macbook

2024-03-26 22:04 UTC, pm47 commented
Try with eclipse-temurin:21-jre-alpine

Le mar. 26 mars 2024, 23:01, Tom Smith ***@***.***> a écrit :

> I'm getting "ERROR: failed to solve: eclipse-temurin:17-jre-alpine: no
> match for platform in manifest: not found" running on an M2 Macbook
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ACINQ/phoenixd/pull/17#issuecomment-2021545801>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPPFPRMQKUBXHNBG3FGC4LY2HO2LAVCNFSM6AAAAABFJUNRIOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMRRGU2DKOBQGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-26 22:12 UTC, tsmith123 commented
Changed both to 21 and it seems better but now I'm getting:

"ERROR: failed to solve: process "/bin/sh -c git clone --recursive --branch ${LIGHTNING_KMP_BRANCH}     https://github.com/ACINQ/lightning-kmp .     && test `git rev-parse HEAD` = ${LIGHTNING_KMP_COMMIT_HASH} || exit 1     && ./gradlew publishToMavenLocal -x dokkaHtml" did not complete successfully: exit code: 1"

2024-03-27 13:50 UTC, pm47 commented
Rebased on master. 

> Changed both to 21 and it seems better but now I'm getting:
> "ERROR: failed to solve: process "/bin/sh -c git clone --recursive --branch ${LIGHTNING_KMP_BRANCH} https://github.com/ACINQ/lightning-kmp . && test git rev-parse HEAD = ${LIGHTNING_KMP_COMMIT_HASH} || exit 1 && ./gradlew publishToMavenLocal -x dokkaHtml" did not complete successfully: exit code: 1"

@tsmith123 your issue should be fixed at 5630fa0.

2024-03-27 14:38 UTC, sstone reviewed
Building this docker image  still won't work on macOS arm64 because of https://github.com/gradle/gradle/issues/24875.
It could be fixed by using a glibc-based bistro (ubuntu, ...) or maybe switching to a snapshot version of gradle 8.8 but I'm not sure it's worth it as macOS arm64 is not a production target (and we  already publish a native `phoenixd` exe for macOS arm64).

2024-03-27 17:44 UTC, pm47 commented
So @sstone should work on all 4 combinations linux/macos x64/arm64?

More portability is better for docker I think. Besides, ubuntu 21 + jdk21 seems tailor made for a bitcoin app 😄

2024-03-27 17:54 UTC, pm47 commented
Actually went back to alpine for the final image. Best of both worlds or over the top?

2024-03-27 19:13 UTC, sethforprivacy commented
Dockerfile looks GTG to me, fantasticly simplified approach compared to building from source.

I'll switch to using this as well in mine (will keep my repo just so there can be a published image in GHCR/Dockerhub) with proper credit, of course. Thanks for all of the work on this @pm47!

2024-03-27 19:22 UTC, sethforprivacy commented
I have a few other minor improvements (none necessary, just tweaks and more explicit declaration of things like user:group pairings) in my PR on my own repo here, feel free to take anything that strikes your fancy, no credit etc. necessary.

https://github.com/sethforprivacy/phoenixd-docker/pull/3

2024-03-27 19:32 UTC, sethforprivacy commented
Sorry for the message spam, but I actually just caught a breaking issue with the proposed Dockerfile. This Dockerfile doesn't properly set the file permissions for `/phoenix` which can sometimes cause the image to error out with a permissions issue when run.

See the fix here: https://github.com/sethforprivacy/phoenixd-docker/pull/3/commits/f3a63e0e2ca0fabda05bfa0573e3c9de730bfb0b

2024-03-27 19:47 UTC, sethforprivacy commented
@pm47 seems there is a build issue for ARMv8, can't get it to find a workable Kotlin version. Logs:

https://paste.sethforprivacy.com/?ddbbbdc28345c06d#4DPdDZvXT4CGRBJ7jo1CDnNTUB3Ynkvp5yuMRcMJ3iqX

Not sure if you can access it, but the full Github Action run is here: https://github.com/sethforprivacy/phoenixd-docker/actions/runs/8457575444/job/23169856878?pr=3

2024-03-27 20:40 UTC, pm47 commented
> Edit: Nevermind, seems you can't build ARMv8 using ARMv8 due to Kotlin having no native aarch64 Linux support. Will find another way to distribute ARMv8 images then.

On the contrary, it should work, that is the point of using a jvm build for docker instead of a native one. Seems like gradle tries to build the native version, which we are not going to use anyway.

Will look at your other changes, feel free to suggest changes directly on this PR too!

2024-03-27 21:03 UTC, sethforprivacy requested changes
I think this encompasses all of my minor changes/improvements, feel free to take or leave any and all of them as you see fit :)

2024-03-27 21:03 UTC, sethforprivacy commented on .docker/Dockerfile
> +RUN apk add --no-cache bash
Prevent potential issues installing without also updating apk cache:

```suggestion
RUN apk add --update --no-cache bash
```

2024-03-27 21:03 UTC, sethforprivacy commented on .docker/Dockerfile
> +FROM eclipse-temurin:21-jre-alpine
Explicitly set label for final stage:

```suggestion
FROM eclipse-temurin:21-jre-alpine as FINAL
```

2024-03-27 21:03 UTC, sethforprivacy commented on .docker/Dockerfile
> +    && apt clean
Better apt cleanup:

```suggestion
    && apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

2024-03-27 21:03 UTC, sethforprivacy commented on .docker/Dockerfile
> +# Ubuntu image for building, for compatibility with macOs arm64
```suggestion
# Use Ubuntu image for building for compatibility with macOS arm64 builds
```

2024-03-27 21:03 UTC, sethforprivacy commented on .docker/Dockerfile
> +COPY --chown=phoenix --from=BUILD /phoenixd/build/distributions/phoenix-*-jvm.tar .
Explicitly set group in chown flag:

```suggestion
COPY --chown=phoenix:phoenix --from=BUILD /phoenixd/build/distributions/phoenix-*-jvm.tar .
```

2024-03-28 11:18 UTC, pm47 commented on .docker/Dockerfile
> +USER phoenix
We don't need to create `.phoenix`, this would have hidden the bug fixed in #15.

2024-03-28 12:34 UTC, sstone commented
Building `phoenixd` in docker is hard and there does not seem to be a way to make it work for `linux/arm64` (which would be a real production target), even if issues with gradle on alpine are solved.
Why not remove the build step and have the docker file simply download the released JVM binaries and use them directly ? that would give us a simple docker file that would work on all targets the JVM version supports (including `macos arm64/x64` and `linux arm64/x64`) ?

2024-03-28 13:25 UTC, sethforprivacy commented on .docker/Dockerfile
> +USER phoenix
Understood, removed that in my Dockerfile now as well.

2024-03-28 13:26 UTC, sstone commented
> Building `phoenixd` in docker is hard and there does not seem to be a way to make it work for `linux/arm64` 

@pm47 found a workaround (see #25)

2024-03-28 13:28 UTC, sethforprivacy commented on .docker/Dockerfile
> +USER phoenix
Updated to only chown and not create any directories.

2024-03-28 13:37 UTC, sethforprivacy commented
> @sethforprivacy the build should pass on arm at [75247e4](https://github.com/ACINQ/phoenixd/commit/75247e4de22ca5213c5012687975f0ccb25f205e) (current master tip)

Testing now! https://github.com/sethforprivacy/phoenixd-docker/actions/runs/8468177452/job/23200542411?pr=3

2024-03-28 13:55 UTC, sethforprivacy commented on .docker/Dockerfile
> +USER phoenix
@pm47 when I don't create the directory explicitly I always get a failure when trying to run the Docker image in Github Actions:

```
Exception in thread "main" java.io.FileNotFoundException: /phoenix/.phoenix/seed.dat (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at okio.Okio__JvmOkioKt.sink(JvmOkio.kt:173)
	at okio.Okio.sink(Unknown Source)
	at okio.Okio__JvmOkioKt.sink$default(JvmOkio.kt:173)
	at okio.Okio.sink$default(Unknown Source)
	at okio.JvmSystemFileSystem.sink(JvmSystemFileSystem.kt:101)
	at fr.acinq.lightning.bin.conf.SeedKt.getOrGenerateSeed(Seed.kt:52)
	at fr.acinq.lightning.bin.Phoenixd$special$$inlined$defaultLazy$default$1.invoke(TransformAll.kt:253)
	at fr.acinq.lightning.bin.Phoenixd$special$$inlined$defaultLazy$default$1.invoke(TransformAll.kt:97)
	at com.github.ajalt.clikt.parameters.options.OptionWithValuesImpl.finalize(OptionWithValues.kt:221)
	at com.github.ajalt.clikt.internal.FinalizationKt.finalizeParameters(Finalization.kt:61)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:24[8](https://github.com/sethforprivacy/phoenixd-docker/actions/runs/8468177452/job/23200542411?pr=3#step:6:9))
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:41)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:457)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:454)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:474)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:481)
	at fr.acinq.lightning.bin.MainKt.main(Main.kt:72)
	```

This is fixed 100% of the time when I explicitly create + chown the default data directory. Are you sure that I shouldn't be doing that?

2024-03-28 13:58 UTC, pm47 commented on .docker/Dockerfile
> +USER phoenix
If `phoenixd` is run by user `phoenix`, and user `phoenix` has recursive ownership of `/phoenix`, then `phoenixd` should be able to create dir `/phoenix/.phoenix`. We can hide the issue by creating the directory manually, but this is suspicious

2024-03-28 14:08 UTC, sstone commented on .docker/Dockerfile
> +USER phoenix
I think that the pb here is the ` VOLUME [ "/phoenix/.phoenix" ]` instruction which imho should not be needed (though I'm no docker expert).

2024-03-28 14:43 UTC, sethforprivacy commented on .docker/Dockerfile
> +USER phoenix
Testing in https://github.com/sethforprivacy/phoenixd-docker/pull/3/commits/b39e88b73721687342fd823eee94163e9c6f025b

2024-03-28 14:48 UTC, pm47 commented on .docker/Dockerfile
> +USER phoenix
From https://serverfault.com/a/984599:

>Named volumes are initialized when first created to the contents of the image at the mount location. That initialization includes the owner and permissions. If /backup does not exist in your image, then an empty directory will be created and owned by root.

So in our case `/phoenix` is owned by `phoenix`, but `/phoenix/.phoenix` was owned by `root`. Your fix should work.

2024-03-28 14:52 UTC, sethforprivacy commented on .docker/Dockerfile
> +USER phoenix
You figured it out, @sstone :) Working perfectly now after changing the VOLUME directive, somehow that must have been creating it with bad permissions!

2024-03-28 14:52 UTC, sethforprivacy commented on .docker/Dockerfile
> +USER phoenix
Please reject this suggestion @pm47, no longer needed.

2024-03-28 14:53 UTC, sethforprivacy commented on .docker/Dockerfile
> +VOLUME [ "/phoenix/.phoenix" ]
Fix permissions by only mounting the home directory:
```suggestion
VOLUME [ "/phoenix" ]
```

2024-03-28 14:59 UTC, pm47 commented
Looking pretty good I think. Will update branch/version after next release

2024-03-29 08:36 UTC, tsmith123 commented
Not sure if this Dockerfile is in its final state yet but it doesn't work for me on an M2 Macbook.

<img width="983" alt="image" src="https://github.com/ACINQ/phoenixd/assets/7639854/c8e796f8-2b68-4d8b-a36e-08948cd39a93">

2024-03-29 12:18 UTC, sethforprivacy commented
> Not sure if this Dockerfile is in its final state yet but it doesn't work for me on an M2 Macbook.
> 
> <img alt="image" width="983" src="https://private-user-images.githubusercontent.com/7639854/317998605-c8e796f8-2b68-4d8b-a36e-08948cd39a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTQ5OTUsIm5iZiI6MTcxMTcxNDY5NSwicGF0aCI6Ii83NjM5ODU0LzMxNzk5ODYwNS1jOGU3OTZmOC0yYjY4LTRkOGItYTM2ZS0wODk0OGNkMzlhOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMTIxODE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU3YjYxNmY0NWQzNzRmMjliYjdkNDAwZGY0ZTYyZjBlZDYwMDM0YWIzNTI1MzQwOTQ2OGUzMDBjMTA3MGU4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JC_AvoOvjnsMFc6czs61DY-okXEjIDYJxAZfsF2mflI">

This issue was fixed in master, so next release will include the fix (per https://github.com/ACINQ/phoenixd/pull/17#issuecomment-2025186287). It was discussed at length above if you want more details on it!

2024-03-29 13:59 UTC, pm47 commented
@tsmith123 Please confirm you are getting this error when using the Dockerfile at commit [f255a11](https://github.com/ACINQ/phoenixd/pull/17/commits/f255a11d798bb13ea5f79374c1e7354c501cdb24).

2024-03-30 04:33 UTC, dnjooiopa commented
> @tsmith123 Please confirm you are getting this error when using the Dockerfile at commit [f255a11](https://github.com/ACINQ/phoenixd/pull/17/commits/f255a11d798bb13ea5f79374c1e7354c501cdb24).

I got the same error on an M1 MacBook.
Commit f255a11d798bb13ea5f79374c1e7354c501cdb24
![image](https://github.com/ACINQ/phoenixd/assets/34341154/6000677b-f2e0-4e5c-8c6d-a2e436c8bcb7)

2024-04-04 21:31 UTC, pm47 commented
@tsmith123 @dnjooiopa Please try again with at [1c3a7ab](https://github.com/ACINQ/phoenixd/pull/17/commits/1c3a7ab5fea071b8987a20134d6bb1dcf44121a4) thanks!

2024-04-06 02:06 UTC, dnjooiopa commented
> @tsmith123 @dnjooiopa Please try again at [1c3a7ab](https://github.com/ACINQ/phoenixd/pull/17/commits/1c3a7ab5fea071b8987a20134d6bb1dcf44121a4) thanks!

Great! Docker is now successfully building on my M1 Mac.

2024-04-10 15:43 UTC, merged

2024-04-10 15:53 UTC, sethforprivacy commented
Amazing work on this, thank you @pm47! I've merged a very similar Dockerfile with automatic builds via Github Actions, so anyone who wants to use a ready-built image for phoenixd can use it easily:

https://github.com/sethforprivacy/phoenixd-docker/pkgs/container/phoenixd

The latest v0.1.4 version is building now and will be available shortly.